name: banana_challenge_commons
description: Banana challenge commons
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dev_dependencies:
  freezed: ^2.3.2
  json_annotation: ^4.8.0
  melos: ^3.0.1
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0
  build_runner: ^2.3.3
dependencies:
  freezed_annotation: ^2.2.0
  json_serializable: ^6.6.1

